### ISSUE TITLE
Not respecting the python-interpreter-path

### ISSUE THREAD

**Issue by maurosilber** [facebook/pyrefly#1396]
### Describe the Bug

When python is installed in the same environment as `pyrefly`, it does not respect the `python-interpreter-path` setting.

A minimal working example using `pixi` with two environments (`default` and `lint`):

```toml
[project]
name = "pyrefly-issue"
requires-python = ">= 3.11"

[tool.pixi.workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.environments]
lint = { features = ["lint"], no-default-feature = false }  # change this to true

[tool.pixi.feature.lint.dependencies]
pyrefly = "==0.39.1"

[tool.pyrefly]
python-interpreter-path = ".pixi/envs/default/bin/python"
```

There are two environments:
- `.pixi/envs/default` which has python
- `.pixi/envs/lint` which has python and pyrefly

Running:
```
pixi run -e lint pyrefly dump-config
```
it detects the python from the lint environment, ignoring the `python-interpreter-path` setting:
```
INFO Checking project configured at `.../pyproject.toml`
Configuration at `.../pyproject.toml`
  Using interpreter: .../.pixi/envs/lint/bin/python3
...
```

If we exclude python from the lint environment (by not inheriting the default feature), it respects the setting:
```diff
[tool.pixi.environments]
-lint = { features = ["lint"], no-default-feature = false }
+lint = { features = ["lint"], no-default-feature = true }
```
```
INFO Checking project configured at `.../pyproject.toml`
Configuration at `.../pyproject.toml`
  Using interpreter: .../.pixi/envs/default/bin/python
...
```

And if we remove the setting:
```diff
[tool.pyrefly]
-python-interpreter-path = ".pixi/envs/default/bin/python"
```
it finds the system python:
```
 INFO Checking project configured at `.../pyproject.toml`
Configuration at `.../pyproject.toml`
  Using interpreter: /usr/bin/python3
...
```
so, it was working in the previous case.

**Comment by kinto0** [comment]
I think @connernilsen might have fixed this [here](https://github.com/facebook/pyrefly/commit/4ba157c30ae29a5faa9720a287c86f924a411d42?fbclid=IwY2xjawNs3utleHRuA2FlbQIxMQBicmlkETEwT1NOYURzTXBab2JMdUJ3AR4MNgBK9A-PZvcdHM6rpUE4_staxtqqjBk-e2RENhi_2ssaJuEKCZusOo7X9A_aem_NN-aTnIfiJFnq090jv3fjA) already. @connernilsen  can you confirm?

**Comment by connernilsen** [comment]
Oh yeah, I think that should fix it. Great timing with this question lol.

I think we should be doing another release soon, if one hasn't gone out already.

**Comment by maurosilber** [comment]
I tried with the new release, `0.39.1`, but the issue persists: if python is installed in the same environment as pyrefly, it ignores the `python-interpreter-path` setting.

**Comment by kinto0** [comment]
> I tried with the new release, `0.39.1`, but the issue persists: if python is installed in the same environment as pyrefly, it ignores the `python-interpreter-path` setting.

looks like we haven't actually gotten around to a release yet. i'll kick one off right now. sorry about the back/forth!

**Comment by kinto0** [comment]
started. it's running a bunch of tests but it should be available within the hour as 0.39.2

**Comment by maurosilber** [comment]
I just tested with the build artifact from ca4b47aa7fa44fcb77335099fa7ac2f28bf279cd and it works now. Thanks!
