### ISSUE TITLE
argparse.Namespace not well-supported

### ISSUE THREAD

**Issue by zsol** [facebook/pyrefly#23]
I tried running pyrefly 0.4.0 over at https://github.com/zsol/dotslash-python/pull/8, and there are only two (OK maybe three) issues that would make it typecheck cleanly.

The most annoying one is that Namespace objects expect attribute accesses for dynamically defined attributes, which Pyrefly is currently not aware of, causing [errors](https://github.com/zsol/dotslash-python/actions/runs/13863663858/job/38797820772?pr=8#step:5:13).

Super simple repro (doesn't work in the browser-based playground, no stdlib):
```py
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("foo")
args = parser.parse_args()
args.foo  # this should not be a type error
```

**Comment by grievejia** [comment]
I think we just need `__getattr__` support for this. Shouldn't be too hard. Can take a look.

**Comment by grievejia** [comment]
Fixed in 66ee262c731134b797574e14e87200214f2b1415

**Comment by zsol** [comment]
Nice, only one error remaining in https://github.com/zsol/dotslash-python/pull/8
