### ISSUE TITLE
Class definition bindings should not be visible in nested scopes

### ISSUE THREAD

**Issue by grievejia** [facebook/pyrefly#264]
### Describe the Bug

Minimal repro:
```python
x = 1

class A:
    x = 4
    [reveal_type(x) for a in range(1)]

    class B:
        reveal_type(x)
```
Expected: Both reveals produce `Literal[2]`
Actual: Both reveals produce`Literal[1]`

### Sandbox Link

https://pyrefly.org/sandbox/?code=B4AgvCCMBQ0MYBsCGBnFICCAuaI8lAgBZd8BtAJwFMA3KpBAfQBcBPAByoApgBKEAGYB7CiCQgAlgDsQFJFIDm3SLwC6sfCESp0AIRybN1OgxYdufaEA

**Comment by fangyi-zhou** [comment]
This seems to have been fixed?

**Comment by rchen152** [comment]
I believe this is still broken (and the issue description isn't quite right). When I print the two `x`s, I get `1` for both, but Pyrefly says `Literal[4]`.

Edit: I fixed the description.

**Comment by fangyi-zhou** [comment]
Got it, I didn't realise `x = 4` was under a class because I misread it as a function. Sorry for the confusion

**Comment by rchen152** [comment]
No worries! I had to run this one through an interpreter because I was unsure about it myself.

**Comment by stroxler** [comment]
@fangyi-zhou Thanks for the fix! It's mostly correct.

Unfortunately we ran into two issues that were causing enough harm that we temporarily reverted the change:
- Pyrefly models comprehension scopes wrong, the iterator itself (x in `[y for y in x]`) is actually in the parent scope, not the comprehension scope. Because of this prexisting issue, the fix in [2ef5a54](https://github.com/facebook/pyrefly/commit/2ef5a5431e34d29e8a7ba8153943ba35781c72fb) caused Pyrefly
  to be unable to handle comprehensions in class scope (#1073)
- It turns out that we probably don't need an exception for static typing use cases, what we really need is an
  exception for function parameter scopes - terms from the class body can be used in function parameter lists, not
  only as type annotations but also as default values

If you'd like to take another stab at this, let us know. The comprehension issue is preexisting but interacts with this change; if it's helpful I could try to fix it first.

**Comment by fangyi-zhou** [comment]
Hey @stroxler, thanks for the investigation. I will raise a diff to reland my original fix, but leaving the case broken for comprehensions, since in the current design it's difficult to tell whether the variable being looked up is in the position of iterator or the comprehension --- will leave that to you.
