### ISSUE TITLE
Pyrefly langauge server crash

### ISSUE THREAD

**Issue by Axibord** [facebook/pyrefly#347]
### Describe the Bug

I don't know what it is exactly, but I think it's interfering with Pylance because as reported in 2 other issues, we lose semantic highlighting, autocomplete and VSCode intellicode extension can't load so you must disable/uninstall it.

<img width="1278" alt="Image" src="https://github.com/user-attachments/assets/67370aa7-7430-4963-9a7b-d730960020f8" />
<img width="382" alt="Image" src="https://github.com/user-attachments/assets/a05489fb-f35d-452c-95b9-fbe18d0c465b" />
<img width="617" alt="Image" src="https://github.com/user-attachments/assets/4b6e2e40-5760-4ec8-a98d-2f335dbed4bf" />

**Comment by ndmitchell** [comment]
Eek, this definitely isn't good. Sorry for breaking Pylance. We'll take a look.

**Comment by cnydo** [comment]
> Eek, this definitely isn't good. Sorry for breaking Pylance. We'll take a look.

I can confirm I have the same problem. My output tab is actually empty. After I uninstall the extension, everything works normally again

![Image](https://github.com/user-attachments/assets/1ccb09e5-f995-4879-b56f-02eb06916001)

![Image](https://github.com/user-attachments/assets/49d2c069-2e43-462a-b191-d640b8dff686)

**Comment by ndmitchell** [comment]
I managed to reproduce this. Fix in #355 - required completions, one long and one short module, a property with overload - quite a bunch of things. But will be fixed once I get a review and we make a new release (hopefully by Tuesday at the latest)

**Comment by ndmitchell** [comment]
This is fixed in the latest release 0.17

**Comment by Axibord** [comment]
> This is fixed in the latest release 0.17

I tried it today, I still don't have Pylance highlighting and autocomplete. As soon as I install the VSCode "Pyrefly" extension, I immediately lose everything. (I'm using UV package manager with 3.13 python version, if it helps). But it's not crashing, so it's an improvment.

**Comment by ndmitchell** [comment]
Sorry @Axibord, I don't think anyone was monitoring closed issues. Is this still happening to you?

CC @kinto0 @connernilsen who might be able to help.

**Comment by kinto0** [comment]
Pylance highlighting and autocomplete is expected to disable when Pyrefly is installed. Since this post, we've made a ton of improvements to the point where highlighting and autocomplete should work very well. See the [disableLanguageServices](https://pyrefly.org/en/docs/IDE/#customization) setting if you want to go back to Pylance.

**Comment by connernilsen** [comment]
@Axibord, if you are still having issues/Pyrefly isn't working as you expect it to, please open a new issue an tag us in it. Thanks!

**Comment by Axibord** [comment]
I didn't test it since then. I'll test it again very soon. I guess it's in a much better state. Thanks for your hard work, I'll keep you informed with a new issue if the bug is still present. Thank you!
