### ISSUE TITLE
`+=` is not supported between `@4777` and `Literal[1]`

### ISSUE THREAD

**Issue by MarcoGorelli** [facebook/pyrefly#41]
I haven't yet managed to make a small reproducible example for this one, but if you run

```
git clone https://github.com/narwhals-dev/narwhals.git
cd narwhals
pyrefly check narwhals/_expression_parsing.py
```
then you'll get lots of mysterious errors like
```
ERROR narwhals/_expression_parsing.py:313:17-43: `+=` is not supported between `@4889` and `Literal[1]`
  TODO: Binding::AugAssign attribute base undefined for type: @_ (trying to access __add__) [internal-error]
ERROR narwhals/_expression_parsing.py:313:17-43: `+=` is not supported between `@4889` and `Literal[1]`
  TODO: Binding::AugAssign attribute base undefined for type: @_ (trying to access __iadd__) [internal-error]
ERROR narwhals/_expression_parsing.py:320:17-35: `+=` is not supported between `@4885` and `Literal[1]`
  TODO: Binding::AugAssign attribute base undefined for type: @_ (trying to access __add__) [internal-error]
ERROR narwhals/_expression_parsing.py:320:17-35: `+=` is not supported between `@4885` and `Literal[1]`
  TODO: Binding::AugAssign attribute base undefined for type: @_ (trying to access __iadd__) [internal-error]
ERROR narwhals/_expression_parsing.py:334:10-27: `>` is not supported between `Literal[0] | @4884 | @4885 | @4886` and `Literal[1]`
```

The code just does:
```python
result_n_open_windows = 0
```
then, inside a for-loop
```python
result_n_open_windows += 1
```

**Comment by AA-Turner** [comment]
https://pyrefly.org/try/?code=CYUwZgBAzgDghgWwBQEoIFoB8EByB7AOxAC4AoCCiAiAXggFZzKA3OAGwFcRaIBGJigHcAFgEs23agB4+ABjKVFVCAGo6rTiFJA

```py
def spam() -> None:
    n = 5
    value = 1
    while n < 10:
        n += value
```

**Comment by lolpack** [comment]
I get this error as well. 

`ERROR badge.py:33:9-30: `+=` is not supported between `@12172` and `Literal[1]``

```
for package, package_info in package_report.items():
    has_typed_classifier, has_stubs_only_classifier = check_typed_classifier(package)
    key = (package_info["HasPyTypedFile"], package_info["HasTypeShed"], package_info["HasStubsPackage"], package.startswith("types-") or package.endswith("-stubs"), has_stubs_only_classifier)
    if has_stubs_only_classifier:
        stubs_only_total += 1
```

https://github.com/lolpack/type_coverage_py/blob/main/badge.py#L33

**Comment by ndmitchell** [comment]
Thanks, I'll take this one.

**Comment by ndmitchell** [comment]
Fixed in 6f383dfd73af86cedf445134225b49a65f30a787

**Comment by MarcoGorelli** [comment]
> https://pyrefly.org/try/?code=CYUwZgBAzgDghgWwBQEoIFoB8EByB7AOxAC4AoCCiAiAXggFZzKA3OAGwFcRaIBGJigHcAFgEs23agB4+ABjKVFVCAGo6rTiFJA
> 
> def spam() -> None:
>     n = 5
>     value = 1
>     while n < 10:
>         n += value

thanks for the smaller repro - however, I don't think this completely captures the issue I was encountering, as it's still present with Pyrefly 0.10.1 (https://github.com/facebook/pyrefly/issues/86)
