### ISSUE TITLE
"inconsistent types when breaking cycles" error on loop

### ISSUE THREAD

**Issue by rchen152** [facebook/pyrefly#528]
### Describe the Bug

Repro:
```
from typing import Iterable, Iterator, cast

def iterate[T](*items: T | Iterable[T]) -> Iterator[T]:
    for item in items:
        if isinstance(item, str):
            yield cast(T, item)
        elif isinstance(item, Iterable):
            yield from item
        else:
            yield item
```
Pyrefly emits: "`Iterable[T] | str | T` is not assignable to `Iterable[T] | T` (caused by inconsistent types when breaking cycles)" with a range spanning the entire loop. I'd expect this code to type-check without error.

### Sandbox Link

https://pyrefly.org/sandbox/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCSMApiAIYBGANsQDSEnky70DGZAzjAFDcAmxYJkZkSAbQAqAXQAUAKiQkIHAFxQJUAD4NSlGpKkBKKAFoAfDqa4DK7lHtRguYcWioXy2w++YhSDqhcZCisxDKKrvRcIIZePvFwSMRUfFDsXDIS9BEQhnbxUMlIfgEoQSFhOfREutTEsfkFDonJqaCQHo0+yRzEcU32LSkeQA

**Comment by stroxler** [comment]
This came up when investigating determinism (not a huge surprise, since cycles are one of the scenarios where determinism can be tricky), so I'm going to at least take a look soon

**Comment by stroxler** [comment]
I got held up on this, but I still expect to attempt to simplify looping and flow-merging logic in the next few weeks (well, maybe the next month and a half - if I don't get it done in 2 weeks, I have an oncall and vacation coming up fast).

The general case of hitting this error may be unfixable (handling recursion the way we do can intrinsically fail in weird ways), but I'm confident that smarter loop handling will fix this specific example and most other simple cases where we hit this kind of error.

**Comment by stroxler** [comment]
Fixed for this example (and any code that doesn't reassign in a loop) by [2ac3ded](https://github.com/facebook/pyrefly/commit/2ac3ded91d0da47471c630ea3edc0a937e4d2d59)

**Comment by max0x7ba** [comment]
I use `pyrefly-0.53.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` and still experience this:

```
bad-assignment           Pyrefly detected conflicting types while breaking a dependency cycle: `str | None` is not assignable to `None`. Adding explicit type annotations might possibly help. (lsp)
```

What pyrefly version is free from this bug, please?

**Comment by yangdanny97** [comment]
@max0x7ba 

Do you have a code snippet/example of when this occurs?

**Comment by max0x7ba** [comment]
> [@max0x7ba](https://github.com/max0x7ba)
> 
> Do you have a code snippet/example of when this occurs?

Well, I test drived using `pyrefly lsp` in emacs on my modest codebase with just under 30k lines of Python code, currently linted with mypy. pyrefly is much faster than mypy, indisputably.

However, this `bad-assignment` pyrefly error was just one of the many more false positive errors pyrefly reported subsequently. 

Having worked around all pyrefly false positive errors by minor tweaks to my Python code syntax, pyrefly detects strictly fewer errors than mypy does. Aggravated by false positive errors pyrefly finds in every .py source file.

I made one big commit with small syntactic changes eliminating all pyrefly false positive errors, and, next, reverted my emacs configration back to using mypy. 

I didn't extract pyrefly false positive errors into minimal complete unit-tests because judging from other false positive errors pyrefly reports, like an inner class in an outer derived class deriving the inner base class of the outer base class, pyrefly internal data model seems to lack the notion of inner derived classes, required for type checking such cases correctly with no false positive errors. 

A code snippet work-around for one pyrefly false positive `[bad-assignment]` error from that commit. `cast` fails to fix pyrefly error, requiring a blanket `pyrefly: ignore[bad-assignment]`:

```
-    for symbol_idx, symbol in enumerate(options.symbols):
+    for symbol_idx, symbol in enumerate(cast(Sequence[str], options.symbols)): # pyrefly: ignore[bad-assignment]
```
`options` is created by `argparse.ArgumentParser.parse_args`, with its attribute `symbols` being positional arguments, a list of 0 or more strings:

```
    parser.add_argument("symbols", metavar="SYMBOL", nargs='*', help='Space-separated symbol names.')
```

pyrefly false positive `[bad-assignment]` refers to `symbol` object in `for symbol_idx, symbol in enumerate(options.symbols):` line.

Whereas mypy infers the right types with no false positives anywhere, unlike pyrefly.

**Comment by yangdanny97** [comment]
Hm, those sound like bugs. Is the codebase public?
